apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql-rs-secret
  labels:
    app: mysql-rs-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs-secret-pod
  template:
    metadata:
      labels:
        app: mysql-rs-secret-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-wp
  name: mysql-wp
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
