apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu-ds
  labels:
    daemonSet: nodes
spec:
  selector:
    matchLabels:
      type: gpu
  template:
    metadata:
      labels:
        type: gpu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
