apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-rs
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  # labels:
  #   app: nginx-rs
  name: nginx-rc-service
spec:
  selector:
    app: nginx-rs
  type: NodePort
  ports:
  - protocol: TCP
    port: 81



