apiVersion: v1
kind: Service
metadata:
  labels:
    app: appone
  name: appone-servie
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: appone
