apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    hello: world
spec:
  containers:
  - name: hello-world
    image: 50364747/world:v1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    hello: world
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
