apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - image: 50364747/world:v1
    name: helloworld
    - containerPort
      port: 80


---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
